// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBpOjcyjUiNtloIenkWi7XAEQbagYBXHtg",
      authDomain: "music-app-a79f9.firebaseapp.com",
      projectId: "music-app-a79f9",
      storageBucket: "music-app-a79f9.appspot.com",
      messagingSenderId: "485709580235",
      appId: "1:485709580235:web:a5aca4d29606acc4f1984e"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxs3S6-jR0-B_GY5Hd84UmDtnARXNMtA',
    appId: '1:485709580235:android:929dd0b2f4a536e1f1984e',
    messagingSenderId: '485709580235',
    projectId: 'music-app-a79f9',
    storageBucket: 'music-app-a79f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyISgS4OmbGbSBmJtdgJwDoOP0RUR8Dgw',
    appId: '1:485709580235:ios:af7480008d9b1c6df1984e',
    messagingSenderId: '485709580235',
    projectId: 'music-app-a79f9',
    storageBucket: 'music-app-a79f9.appspot.com',
    iosBundleId: 'com.hien.musicApp',
  );


}